### ISSUE TITLE
Provide a link to the paper

### ISSUE THREAD

**Issue by houfu** [brucewlee/lingfeat#2]
I was curious about the advanced features, and the Readme "highly" suggested that I "read Section 2 and 3 in our EMNLP paper."
However, I couldn't find a link to the paper in the README.MD :weary: 

It's this one right? https://arxiv.org/abs/2109.12258
I think it would be nice to include a link in the README.MD for easy access to other users.
(I could do a simple pull request if it's too troublesome)

Thanks for releasing this here!

**Comment by brucewlee** [comment]
[Published version](https://aclanthology.org/2021.emnlp-main.834/) Here you go! I'll update the citations! Thanks for suggestion :)
