### ISSUE TITLE
Feature Naming issue

### ISSUE THREAD

**Issue by shehzaadzd** [brucewlee/lingfeat#3]
https://github.com/brucewlee/lingfeat/blob/281a9e2f8be9305aad764978aeadd5283d37084c/lingfeat/_AdvancedSemantic/OSKF.py#L90
https://github.com/brucewlee/lingfeat/blob/281a9e2f8be9305aad764978aeadd5283d37084c/lingfeat/_AdvancedSemantic/OSKF.py#L92
https://github.com/brucewlee/lingfeat/blob/281a9e2f8be9305aad764978aeadd5283d37084c/lingfeat/_AdvancedSemantic/OSKF.py#L94
https://github.com/brucewlee/lingfeat/blob/281a9e2f8be9305aad764978aeadd5283d37084c/lingfeat/_AdvancedSemantic/OSKF.py#L96

Should be ORich, OClar, ONois, OTopic respectively

**Comment by brucewlee** [comment]
Thanks! I'll fix the namings :)
